### ISSUE TITLE
invalid input value for enum project_tier: \"FREE\"

### ISSUE THREAD

**Issue by thorwebdev** [feedbackcentral/feedbackcentral#19]
Hitting an issue when trying to create a new project :(

```js
{
    "name": "Thortest",
    "owner_id": "9c60b0f0-d430-4b82-8e06-d67ccac0ace5",
    "tier": "FREE"
}
// error
{
    "message": "invalid input value for enum project_tier: \"FREE\"",
    "code": "22P02",
    "details": null,
    "hint": null
}
```
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/5748289/163124612-04e1c935-f6ae-4f71-9888-1b438eaea4cc.png">

**Comment by Olyno** [comment]
Ooooh noooo. I just fixed it now, hopefully it's not too late :/

**Comment by thorwebdev** [comment]
Sweet, thanks, works now. QQ, did you end up implementing the functions? https://github.com/feedbackcentral/feedbackcentral/blob/main/supabase/functions/classify_feedback/index.ts doesn't have the code in it. Would be awesome to see an example of using OpenAI API :)

**Comment by HarryET** [comment]
> Sweet, thanks, works now. QQ, did you end up implementing the functions? https://github.com/feedbackcentral/feedbackcentral/blob/main/supabase/functions/classify_feedback/index.ts doesn't have the code in it. Would be awesome to see an example of using OpenAI API :)

@thorwebdev yeah! We did do it it just didn't get merged, the code is here: https://github.com/feedbackcentral/feedbackcentral/blob/edfa62a8928dd46b675160df26a52d4bd8cde00c/supabase/functions/classify_feedback/index.ts

I would hope to have that PR tidied up and merged soon

**Comment by thorwebdev** [comment]
@HarryET ah, nice. if you can, would be cool to add these functions to https://github.com/supabase/supabase/tree/master/examples/edge-functions also :)
